# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74b2925cb250fe7b205244318277341647e12bbfae0cae120ca11328c43c186a0510a1d7fd438dda13126bcdfbcbd87605004953e4a01eda711d36b85d7abe52

test:
  secret_key_base: bde1a3d57f7a64f9b4e5e0f6bc61fb99b8b9c63188a01ac78b57b9be29fc45dfb4f710048a5bda849219d70f9d1d1e324cc09382ef8b4277f4a9cf52edc9b35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
